# Generated by Django 3.2.9 on 2022-03-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_sim', to='simulation.step')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_sim', to='simulation.step')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulation')),
            ],
        ),
    ]
