# Generated by Django 3.2.9 on 2022-03-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_sim', to='simulation.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_sim', to='simulation.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
