# Generated by Django 3.2.9 on 2022-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_auto_20220313_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='video_link',
        ),
        migrations.AddField(
            model_name='step',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
