# Generated by Django 3.2.9 on 2022-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
